version: "3.7"
services:
  fluentd-elasticsearch:
    image: longsube/fluentd-elasticsearch:1.0
    volumes:
      - type: bind
        source: /etc/localtime
        target:  /usr/share/zoneinfo/Asia/Ho_Chi_Minh
      - type: bind
        source: /var/log
        target: /var/log
    environment:
      FLUENTD_CONF: 'fluent.conf'
      FLUENTD_HOSTNAME: '{{.Node.Hostname}}'
    ports:
      - published: 24224
        target: 24224
        mode: host
      - published: 5140
        target: 5140
        mode: host
      - published: 24224
        target: 24224
        mode: host
        protocol: udp
      - published: 5140
        target: 5140
        mode: host
        protocol: udp
    user: root
    configs:
      - source: fluent-elasticsearch-conf.v1
        target: /fluentd/etc/fluent.conf
    networks:
      - private
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.platform.os == linux]

networks:
  private:
    external: true

configs:
  fluent-elasticsearch-conf.v1:
    file: ./fluentd.conf
